# SITE CONFIGURATION
title: labexam # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  this is labexam
baseurl: "/fatemehr" # the subpath of your site, e.g. /blog
url: "https://FatemehRazzaghy.github.io/labexam" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: fatemehr
  links:
    - https://twitter.com/fatemeh
    - https://www.facebook.com/fatemeh
    - https://www.linkedin.com/in/fatemeh
    - https://plus.google.com/fatemeh
    - https://github.com/fatemeh
    - https://keybase.io/fatemeh

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/WIN_20240110_12_54_18_Pro.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: fatemeh@gmain.com # email for form submission

twitter_username: fatemehr # replace with your_twitter_username or comment to remove link from footer
github_username:  fatemehr # replace with your_github_username or comment to remove link from footer
instagram_username: fatemehr # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: fatemehr # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - WIN_20240110_12_54_18_Pro.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
